apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx-rc
spec:
  template:  # this is our pod definition with which k8s will create pods
    metadata:
      name: nginx-rc
      labels:
        app: nginx-rc
    spec:
      containers:
         - name: nginx-rc
           image: nginx
  replicas: 2 